Repository fastly/Viceroy, pull requests merged in 2021-07, with the labels that each got.

#29 🚀 Prepare for 0.2.1 release
  CHANGELOG.md
  Cargo.lock
  cli/Cargo.toml
  cli/tests/trap-test/Cargo.lock
  lib/Cargo.toml
Labels: release

#30 🐦 update crates to new development version (0.2.2)
  Cargo.lock
  cli/Cargo.toml
  cli/tests/trap-test/Cargo.lock
  lib/Cargo.toml
Labels: maintenance, release

#37 🧹 Tidy up logging and error output
  Cargo.lock
  cli/src/opts.rs
  lib/Cargo.toml
  lib/src/error.rs
  lib/src/execute.rs
  lib/src/wiggle_abi/dictionary_impl.rs
  lib/src/wiggle_abi/geo_impl.rs
  lib/src/wiggle_abi/req_impl.rs
  lib/src/wiggle_abi/uap_impl.rs
Labels: logging, maintenance

#39 Add a Code of Conduct to Viceroy and Contributing file
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#38 Have CI use --locked flag for cargo commands
  Cargo.lock
  Makefile
  cli/tests/trap-test/Cargo.lock
  test-fixtures/Cargo.lock
Labels: ci, maintenance

#45 Prepare for 0.2.2 release
  CHANGELOG.md
  Cargo.lock
  cli/Cargo.toml
  lib/Cargo.toml
Labels: release

#49 🌸 Cherry-pick `trap-test` lockfile update
  cli/tests/trap-test/Cargo.lock
Labels: bug, ci

#48 Allow host overrides in TOML configuration
  cli/tests/common.rs
  cli/tests/http-semantics.rs
  cli/tests/upstream-async.rs
  cli/tests/upstream-streaming.rs
  cli/tests/upstream.rs
  lib/src/config/backends.rs
  lib/src/config/unit_tests.rs
  lib/src/error.rs
  lib/src/upstream.rs
Labels: feature-ux
