Repository fastly/Viceroy, pull requests merged in 2022-02, with the labels that each got.

#126 🚀 `0.2.10` release
  CHANGELOG.md
  Cargo.lock
  cli/Cargo.toml
  cli/tests/trap-test/Cargo.lock
  doc/RELEASING.md
  lib/Cargo.toml
  test-fixtures/Cargo.lock
Labels: release

#131 📦 Release v0.2.11
  CHANGELOG.md
  Cargo.lock
  cli/Cargo.toml
  cli/tests/trap-test/Cargo.lock
  doc/RELEASING.md
  lib/Cargo.toml
  test-fixtures/Cargo.lock
Labels: release

#132 🍽 Combine integration test executables for faster builds
  cli/tests/integration/body.rs
  cli/tests/integration/common.rs
  cli/tests/integration/downstream_req.rs
  cli/tests/integration/env_vars.rs
  cli/tests/integration/http_semantics.rs
  cli/tests/integration/logging.rs
  cli/tests/integration/main.rs
  cli/tests/integration/request.rs
  cli/tests/integration/response.rs
  cli/tests/integration/sending_response.rs
  cli/tests/integration/sleep.rs
  cli/tests/integration/upstream.rs
  cli/tests/integration/upstream_async.rs
  cli/tests/integration/upstream_streaming.rs
  cli/tests/trap-test/src/main.rs
Labels: maintenance

#133 📈 Split `trap-test` into a separate CI job
  .github/workflows/test.yml
  Makefile
Labels: ci, maintenance
